# Shops in the Mistwood region

[[shops]]
id = "mistwood_herbs"
owner_entity_id = "herbalist_yavanna"
location_id = "mistwood_apothecary"
shop_type = "apothecary"

[[shops.stock]]
item_id = "healing_potion"
quantity = 5
base_price = 45
base_stock = 5

[[shops.stock]]
item_id = "antidote"
quantity = 5
base_price = 15
base_stock = 5

[[shops.stock]]
item_id = "healing_herb"
quantity = 15
base_price = 2
base_stock = 15

[[shops.stock]]
item_id = "moonpetal"
quantity = 8
base_price = 8
base_stock = 8

[[shops.stock]]
item_id = "herbalism_kit"
quantity = 2
base_price = 5
base_stock = 2


[[shops]]
id = "thalion_bows"
owner_entity_id = "bowyer_thalion"
location_id = "silverleaf_bowyer"
shop_type = "smithy"

[[shops.stock]]
item_id = "shortbow"
quantity = 3
base_price = 25
base_stock = 3

[[shops.stock]]
item_id = "longbow"
quantity = 2
base_price = 50
base_stock = 2

[[shops.stock]]
item_id = "dagger"
quantity = 5
base_price = 2
base_stock = 5

[[shops.stock]]
item_id = "leather_armor"
quantity = 2
base_price = 10
base_stock = 2


[[shops]]
id = "ranger_supply"
owner_entity_id = "ranger_silvan"
location_id = "ranger_outpost"
shop_type = "general"

[[shops.stock]]
item_id = "rations"
quantity = 15
base_price = 1
base_stock = 15

[[shops.stock]]
item_id = "healing_potion"
quantity = 3
base_price = 50
base_stock = 3

[[shops.stock]]
item_id = "hempen_rope"
quantity = 8
base_price = 1
base_stock = 8

[[shops.stock]]
item_id = "torch"
quantity = 10
base_price = 1
base_stock = 10

[[shops.stock]]
item_id = "antidote"
quantity = 3
base_price = 15
base_stock = 3

[[shops.stock]]
item_id = "bedroll"
quantity = 3
base_price = 2
base_stock = 3
